modLoader="javafml" 
loaderVersion="[34,)" 
license="Powered by Hummel009"

[[mods]]
modId="trop"
version="Version 4.0"
displayName="The Rings of Power Mod"
logoFile="logo.png"
credits="Hummel009"
authors="Hummel009"
description='''
This mod adds the rings of power from LOTR to MC 1.16.5
'''
[[dependencies.tut]]
    modId="forge" 
    mandatory=true 
    versionRange="[34,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.tut]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"