modLoader = "javafml"
loaderVersion = "[0,)"
license = "GPL-3.0-only"
logoFile = "logo.png"

[[mods]]
modId = "trop"
version = "24.02.29"
displayName = "The Rings of Power"
authors = "Hummel009"
description = '''This mod adds Rings of Power from the Lord of the Rings to Minecraft.'''

[[dependencies.trop]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trop]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4]"
ordering = "NONE"
side = "BOTH"