modLoader = "javafml"
loaderVersion = "[0,)"
license = "GPL-3.0-only"
logoFile = "logo.png"

[[mods]]
modId = "trop"
version = "24.10.09"
displayName = "The Rings of Power"
authors = "Hummel009"
description = '''This mod adds Rings of Power from the Lord of the Rings to Minecraft.'''

[[dependencies.trop]]
modId = "forge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trop]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1]"
ordering = "NONE"
side = "BOTH"