name: Java CI with Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build_modern:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: compiled-artifact
          path: |
            ./1.3.2/build/libs/*.jar
            ./1.4.7/build/libs/*.jar
            ./1.5.2/build/libs/*.jar
            ./1.6.4/build/libs/*.jar
            ./1.7.10/build/libs/*.jar
            ./1.12.2/build/libs/*.jar
            ./1.13.2/build/libs/*.jar
            ./1.14.4/build/libs/*.jar
            ./1.15.2/build/libs/*.jar
            ./1.16.5/build/libs/*.jar
            ./1.17.1/build/libs/*.jar
            ./1.18.2/build/libs/*.jar
            ./1.19.4/build/libs/*.jar
            ./1.20.4/build/libs/*.jar
  build_legacy:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ '1.8.9', '1.9.4', '1.10.2', '1.11.2' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 8
        uses: actions/setup-java@main
        with:
          java-version: '8'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          build-root-directory: ./${{matrix.version}}
          arguments: build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: compiled-artifact
          path: ./${{ matrix.version }}/build/libs/*.jar